import type { Role } from "./types";

export const roles: Role[] = [
  {
    id: "independent-fullstack-agentic",
    company: "Independent",
    title: "Full Stack & Agentic Systems Developer",
    start: "May 2026",
    end: "Present",
    location: "Remote",
    stack: ["TypeScript", "Next.js", "Cloudflare Workers", "Claude AI", "Cursor"],
    tags: ["Web", "AI"],
    bullets: [
      "Built a full stack web games platform (Klondike Solitaire, Word Guess) with daily puzzle scheduling and shared domain logic in a monorepo.",
      "Designed agentic orchestration workflows with Claude AI and Cursor to accelerate product development.",
      "Deployed to Cloudflare Workers from a turborepo workspace.",
    ],
  },
  {
    id: "independent-mobile",
    company: "Independent",
    title: "Mobile Developer",
    start: "Feb 2026",
    end: "Present",
    location: "Remote",
    stack: ["Flutter", "Dart", "Android"],
    tags: ["Mobile"],
    bullets: [
      "Built an Android app replacing physical smart TV remotes, including device discovery, remote input mapping, and a one-handed touch UI.",
    ],
  },
  {
    id: "sovrun",
    company: "Sovrun (formerly BreederDAO)",
    title: "Game Developer",
    start: "Aug 2023",
    end: "Jan 2026",
    location: "Remote",
    stack: ["Unity", "Unreal"],
    tags: ["Games"],
    bullets: [
      "Contributed to experimental games and simulations R&D spanning blockchain, autonomous worlds, AI simulations, and multiplayer systems.",
      "Collaborated across design, research, blockchain, and AI teams to ship prototypes and live features.",
    ],
  },
  {
    id: "neeuro",
    company: "Neeuro PTE LTD",
    title: "Lead App Developer",
    start: "Oct 2016",
    end: "Jan 2026",
    location: "Remote",
    stack: ["Unity 3D"],
    tags: ["Games", "Mobile"],
    bullets: [
      "Led development of live mobile games and cognitive training apps in Unity, integrating EEG/BCI hardware.",
      "Shipped titles on Android and iOS, driving performance optimization and cross-functional collaboration with design, research, and backend teams.",
    ],
  },
  {
    id: "virtual-labs",
    company: "Virtual Labs",
    title: "Senior Unreal Engine Developer",
    start: "Feb 2022",
    end: "Nov 2022",
    location: "Remote",
    stack: ["Unreal"],
    tags: ["Games", "Web"],
    bullets: [
      "Built a multiplayer metaverse in Unreal Engine with realtime interactions, UI, and account systems.",
      "Delivered Pixel Streaming to the web for browser-based access to the experience.",
    ],
  },
  {
    id: "crazyshark",
    company: "CrazyShark",
    title: "Lead Unity 3D Developer",
    start: "May 2015",
    end: "Oct 2015",
    location: "Remote",
    stack: ["Unity"],
    tags: ["Games"],
    bullets: [
      "Led mobile game projects from prototype through release in Unity.",
    ],
  },
  {
    id: "cylindo",
    company: "Cylindo (formerly LoveMyHome)",
    title: "Junior Unity 3D Developer",
    start: "Aug 2012",
    end: "Aug 2014",
    location: "Remote",
    stack: ["Unity"],
    tags: ["Games", "Web"],
    bullets: [
      "Built 3D room planners and furniture customization tools for Web and iOS.",
    ],
  },
];
